### ISSUE TITLE
Feedback Sprint 2 

### ISSUE THREAD

**Issue by MarciaMillanao** [CoteVD/scl-2018-05-bc-core-am-datadashboard#2]
Hola chicas!
Estuve revisando el avance que llevan y tengo algunos comentarios:

1.- Les recomiendo usar nombre de identificadores (variables en js, clases o id en html & css) bien descriptivos y en inglés.

2.- Utilicen todo el HTML semántico, con eso me refiero a las etiquetas `<header></header> <section></section> <article></article> <aside></aside> <nav></nav> <footer></footer>`

3.- Utilicen milestones para ver el avance de los issues, esto es como un trello pero en github (similar) , les dejo dos vídeos de guía https://youtu.be/9SZSHGA95x4
https://www.youtube.com/watch?v=nI5VdsVl0FM 

4.- Utilicen comentarios a lo largo de su proyecto en los archivos.

5.- Usen los issues para coordinarse y comunicarse entre ustedes

Vamos con todo.``

**Comment by CoteVD** [comment]
Gracias Marcia! 
Vamos a hacer los cambios que nos mencionas :)

**Comment by floresdani** [comment]
Gracias Marcia! manualmente teníamos complicaciones en replicar la página en su estructura HTML y CSS, nos apoyaremos en Bootstrap.
