### ISSUE TITLE
Cote

### ISSUE THREAD

**Issue by floresdani** [CoteVD/scl-2018-05-bc-core-am-datadashboard#4]
Acepta el pull request para trabajar desde ese cambio

**Comment by CoteVD** [comment]
Acepté todos los pull request, estoy trabajando en cómo sacar la data del JSON :)

**Comment by floresdani** [comment]
agregué una función en data.js de filter pero no sé cómo conectarla con el input search de las estudiantes, además cambié el apellido de Vale jojojo
